// Generated by: pnpm --filter @repo/db generate-types
// Run after `supabase start` to regenerate from your local schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          clerk_user_id: string | null;
          email: string | null;
          full_name: string | null;
          role: "admin" | "professor" | "aluno";
          avatar_url: string | null;
          address: string | null;
          banned: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          clerk_user_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "professor" | "aluno";
          avatar_url?: string | null;
          address?: string | null;
          banned?: boolean;
          created_at?: string;
        };
        Update: {
          clerk_user_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "professor" | "aluno";
          avatar_url?: string | null;
          address?: string | null;
          banned?: boolean;
        };
        Relationships: [];
      };
      alunos: {
        Row: {
          id: string;
          professor_id: string | null;
          profile_id: string | null;
          contact_email: string | null;
          grade: string | null;
          subject_focus: string[] | null;
          notes: string | null;
          monthly_amount: number | null;
          address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id?: string | null;
          profile_id?: string | null;
          contact_email?: string | null;
          grade?: string | null;
          subject_focus?: string[] | null;
          notes?: string | null;
          monthly_amount?: number | null;
          address?: string | null;
          created_at?: string;
        };
        Update: {
          professor_id?: string | null;
          profile_id?: string | null;
          contact_email?: string | null;
          grade?: string | null;
          subject_focus?: string[] | null;
          notes?: string | null;
          monthly_amount?: number | null;
          address?: string | null;
        };
      };
      aluno_contatos: {
        Row: {
          id: string;
          aluno_id: string;
          nome: string;
          telefone: string;
          papel: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          aluno_id: string;
          nome: string;
          telefone: string;
          papel: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          aluno_id?: string;
          nome?: string;
          telefone?: string;
          papel?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "aluno_contatos_aluno_id_fkey";
            columns: ["aluno_id"];
            isOneToOne: false;
            referencedRelation: "alunos";
            referencedColumns: ["id"];
          },
        ];
      };
      materiais: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          file_url: string | null;
          subject: string | null;
          grade_level: string | null;
          uploaded_by: string | null;
          created_at: string;
          created_by_admin_id: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          file_url?: string | null;
          subject?: string | null;
          grade_level?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          created_by_admin_id?: string | null;
        };
        Update: {
          title?: string;
          description?: string | null;
          file_url?: string | null;
          subject?: string | null;
          grade_level?: string | null;
          uploaded_by?: string | null;
          created_by_admin_id?: string | null;
        };
        Relationships: [];
      };
      financeiro: {
        Row: {
          id: string;
          aluno_id: string | null;
          amount: number;
          due_date: string | null;
          paid_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          aluno_id?: string | null;
          amount: number;
          due_date?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          aluno_id?: string | null;
          amount?: number;
          due_date?: string | null;
          paid_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      tarefas: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          due_date: string | null;
          material_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          due_date?: string | null;
          material_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          due_date?: string | null;
          material_id?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      aluno_materiais: {
        Row: {
          id: string;
          aluno_id: string;
          material_id: string;
          assigned_by: string | null;
          assigned_at: string;
        };
        Insert: {
          id?: string;
          aluno_id: string;
          material_id: string;
          assigned_by?: string | null;
          assigned_at?: string;
        };
        Update: {
          aluno_id?: string;
          material_id?: string;
          assigned_by?: string | null;
        };
        Relationships: [];
      };
      tarefa_alunos: {
        Row: {
          id: string;
          tarefa_id: string;
          aluno_id: string;
          status: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes: string | null;
          submission_url: string | null;
          submitted_at: string | null;
          reviewed_at: string | null;
          teacher_feedback: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tarefa_id: string;
          aluno_id: string;
          status?: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes?: string | null;
          submission_url?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          teacher_feedback?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tarefa_id?: string;
          aluno_id?: string;
          status?: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes?: string | null;
          submission_url?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          teacher_feedback?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      relatorios_pedagogicos: {
        Row: {
          id: string;
          professor_id: string;
          aluno_id: string;
          disciplinas: string[];
          carga_horaria: string;
          status_conteudo: string;
          engajamento: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          aluno_id: string;
          disciplinas: string[];
          carga_horaria: string;
          status_conteudo: string;
          engajamento?: number | null;
          created_at?: string;
        };
        Update: {
          professor_id?: string;
          aluno_id?: string;
          disciplinas?: string[];
          carga_horaria?: string;
          status_conteudo?: string;
          engajamento?: number | null;
        };
        Relationships: [];
      };
      registros_lista: {
        Row: {
          id: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_aula: string;
          conteudo_ministrado: string;
          quantidade_acertos: number;
          total_questoes: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_aula: string;
          conteudo_ministrado: string;
          quantidade_acertos: number;
          total_questoes: number;
          created_at?: string;
        };
        Update: {
          professor_id?: string;
          aluno_id?: string;
          disciplina?: string;
          data_aula?: string;
          conteudo_ministrado?: string;
          quantidade_acertos?: number;
          total_questoes?: number;
        };
        Relationships: [];
      };
      notas_provas: {
        Row: {
          id: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_prova: string;
          descricao: string;
          nota: number;
          nota_maxima: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_prova: string;
          descricao?: string;
          nota: number;
          nota_maxima?: number;
          created_at?: string;
        };
        Update: {
          professor_id?: string;
          aluno_id?: string;
          disciplina?: string;
          data_prova?: string;
          descricao?: string;
          nota?: number;
          nota_maxima?: number;
        };
        Relationships: [];
      };
      emails: {
        Row: {
          id: string;
          resend_id: string | null;
          direction: "received" | "sent";
          from_email: string;
          to_emails: string[];
          cc_emails: string[] | null;
          bcc_emails: string[] | null;
          subject: string | null;
          body_html: string | null;
          body_text: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          resend_id?: string | null;
          direction: "received" | "sent";
          from_email: string;
          to_emails: string[];
          cc_emails?: string[] | null;
          bcc_emails?: string[] | null;
          subject?: string | null;
          body_html?: string | null;
          body_text?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          resend_id?: string | null;
          direction?: "received" | "sent";
          from_email?: string;
          to_emails?: string[];
          cc_emails?: string[] | null;
          bcc_emails?: string[] | null;
          subject?: string | null;
          body_html?: string | null;
          body_text?: string | null;
          status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      email_attachments: {
        Row: {
          id: string;
          email_id: string;
          resend_attachment_id: string | null;
          filename: string;
          content_type: string | null;
          size: number | null;
          storage_path: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          email_id: string;
          resend_attachment_id?: string | null;
          filename: string;
          content_type?: string | null;
          size?: number | null;
          storage_path: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email_id?: string;
          resend_attachment_id?: string | null;
          filename?: string;
          content_type?: string | null;
          size?: number | null;
          storage_path?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "email_attachments_email_id_fkey";
            columns: ["email_id"];
            isOneToOne: false;
            referencedRelation: "emails";
            referencedColumns: ["id"];
          },
        ];
      };
      eventos: {
        Row: {
          id: string;
          slug: string;
          titulo: string;
          descricao: string | null;
          preco_centavos: number;
          limite_total_vagas: number;
          capacidade_por_turma: number;
          local_nome: string;
          local_endereco: string;
          local_contato: string;
          horario_geral: string | null;
          sala_turma_1: string | null;
          sala_turma_2: string | null;
          data_sabado_1: string | null;
          data_sabado_2: string | null;
          data_sabado_3: string | null;
          data_sabado_4: string | null;
          ativo: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          titulo: string;
          descricao?: string | null;
          preco_centavos: number;
          limite_total_vagas: number;
          capacidade_por_turma: number;
          local_nome: string;
          local_endereco: string;
          local_contato: string;
          horario_geral?: string | null;
          sala_turma_1?: string | null;
          sala_turma_2?: string | null;
          data_sabado_1?: string | null;
          data_sabado_2?: string | null;
          data_sabado_3?: string | null;
          data_sabado_4?: string | null;
          ativo?: boolean;
          created_at?: string;
        };
        Update: {
          slug?: string;
          titulo?: string;
          descricao?: string | null;
          preco_centavos?: number;
          limite_total_vagas?: number;
          capacidade_por_turma?: number;
          local_nome?: string;
          local_endereco?: string;
          local_contato?: string;
          horario_geral?: string | null;
          sala_turma_1?: string | null;
          sala_turma_2?: string | null;
          data_sabado_1?: string | null;
          data_sabado_2?: string | null;
          data_sabado_3?: string | null;
          data_sabado_4?: string | null;
          ativo?: boolean;
        };
        Relationships: [];
      };
      evento_inscricoes: {
        Row: {
          id: string;
          evento_id: string;
          numero_inscricao: number;
          session_id: string | null;
          nome_aluno: string;
          email_aluno: string;
          whatsapp_aluno: string;
          cpf_aluno: string;
          data_nascimento: string;
          idade_aluno: number;
          serie_atual: "1_ano" | "2_ano" | "3_ano" | "concluido";
          nome_responsavel: string | null;
          whatsapp_responsavel: string | null;
          restricoes_medicas: string | null;
          status_pagamento: "pendente" | "aprovado" | "recusado" | "cancelado";
          forma_pagamento: "pix" | "credit_card" | null;
          gateway: string;
          gateway_payment_id: string | null;
          numero_confirmacao: number | null;
          turma_alocada: 1 | 2 | null;
          horario_turma: string | null;
          sala_alocada: string | null;
          codigo_ingresso: string;
          valor_pago_centavos: number;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          created_at: string;
          pago_em: string | null;
        };
        Insert: {
          id?: string;
          evento_id: string;
          session_id?: string | null;
          nome_aluno: string;
          email_aluno: string;
          whatsapp_aluno: string;
          cpf_aluno: string;
          data_nascimento: string;
          idade_aluno: number;
          serie_atual: "1_ano" | "2_ano" | "3_ano" | "concluido";
          nome_responsavel?: string | null;
          whatsapp_responsavel?: string | null;
          restricoes_medicas?: string | null;
          status_pagamento?: "pendente" | "aprovado" | "recusado" | "cancelado";
          forma_pagamento?: "pix" | "credit_card" | null;
          gateway?: string;
          gateway_payment_id?: string | null;
          numero_confirmacao?: number | null;
          turma_alocada?: 1 | 2 | null;
          horario_turma?: string | null;
          sala_alocada?: string | null;
          codigo_ingresso?: string;
          valor_pago_centavos: number;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          created_at?: string;
          pago_em?: string | null;
        };
        Update: {
          nome_aluno?: string;
          email_aluno?: string;
          whatsapp_aluno?: string;
          cpf_aluno?: string;
          data_nascimento?: string;
          idade_aluno?: number;
          serie_atual?: "1_ano" | "2_ano" | "3_ano" | "concluido";
          nome_responsavel?: string | null;
          whatsapp_responsavel?: string | null;
          restricoes_medicas?: string | null;
          status_pagamento?: "pendente" | "aprovado" | "recusado" | "cancelado";
          forma_pagamento?: "pix" | "credit_card" | null;
          gateway?: string;
          gateway_payment_id?: string | null;
          numero_confirmacao?: number | null;
          turma_alocada?: 1 | 2 | null;
          horario_turma?: string | null;
          sala_alocada?: string | null;
          valor_pago_centavos?: number;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          pago_em?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "evento_inscricoes_evento_id_fkey";
            columns: ["evento_id"];
            isOneToOne: false;
            referencedRelation: "eventos";
            referencedColumns: ["id"];
          },
        ];
      };
      evento_analytics: {
        Row: {
          id: string;
          evento_slug: string;
          tipo_evento:
            | "page_view"
            | "cta_click"
            | "form_started"
            | "form_submitted"
            | "pix_generated"
            | "card_started"
            | "payment_approved";
          session_id: string;
          inscricao_id: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          referrer: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          evento_slug: string;
          tipo_evento:
            | "page_view"
            | "cta_click"
            | "form_started"
            | "form_submitted"
            | "pix_generated"
            | "card_started"
            | "payment_approved";
          session_id: string;
          inscricao_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          referrer?: string | null;
          created_at?: string;
        };
        Update: {
          tipo_evento?:
            | "page_view"
            | "cta_click"
            | "form_started"
            | "form_submitted"
            | "pix_generated"
            | "card_started"
            | "payment_approved";
          inscricao_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          referrer?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "evento_analytics_inscricao_id_fkey";
            columns: ["inscricao_id"];
            isOneToOne: false;
            referencedRelation: "evento_inscricoes";
            referencedColumns: ["id"];
          },
        ];
      };
      evento_checkins: {
        Row: {
          id: string;
          inscricao_id: string;
          dia_numero: 1 | 2 | 3 | 4;
          checkin_at: string;
          validado_por: string | null;
        };
        Insert: {
          id?: string;
          inscricao_id: string;
          dia_numero: 1 | 2 | 3 | 4;
          checkin_at?: string;
          validado_por?: string | null;
        };
        Update: {
          dia_numero?: 1 | 2 | 3 | 4;
          checkin_at?: string;
          validado_por?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "evento_checkins_inscricao_id_fkey";
            columns: ["inscricao_id"];
            isOneToOne: false;
            referencedRelation: "evento_inscricoes";
            referencedColumns: ["id"];
          },
        ];
      };
      evento_email_log: {
        Row: {
          id: string;
          inscricao_id: string;
          tipo_email:
            | "ticket_confirmacao"
            | "guia_preparacao"
            | "mensagem_professor"
            | "mapa_tri"
            | "checklist_evento"
            | "devolutiva_dia1"
            | "devolutiva_dia2"
            | "devolutiva_dia3"
            | "pos_evento";
          enviado_em: string;
        };
        Insert: {
          id?: string;
          inscricao_id: string;
          tipo_email:
            | "ticket_confirmacao"
            | "guia_preparacao"
            | "mensagem_professor"
            | "mapa_tri"
            | "checklist_evento"
            | "devolutiva_dia1"
            | "devolutiva_dia2"
            | "devolutiva_dia3"
            | "pos_evento";
          enviado_em?: string;
        };
        Update: {
          tipo_email?:
            | "ticket_confirmacao"
            | "guia_preparacao"
            | "mensagem_professor"
            | "mapa_tri"
            | "checklist_evento"
            | "devolutiva_dia1"
            | "devolutiva_dia2"
            | "devolutiva_dia3"
            | "pos_evento";
          enviado_em?: string;
        };
        Relationships: [
          {
            foreignKeyName: "evento_email_log_inscricao_id_fkey";
            columns: ["inscricao_id"];
            isOneToOne: false;
            referencedRelation: "evento_inscricoes";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      confirmar_pagamento_evento: {
        Args: {
          p_inscricao_id: string;
          p_gateway_payment_id: string;
          p_forma_pagamento: string;
          p_valor_pago_centavos: number;
        };
        Returns: Database["public"]["Tables"]["evento_inscricoes"]["Row"];
      };
    };
    Enums: Record<string, never>;
  };
}
