// Generated by: pnpm --filter @repo/db generate-types
// Run after `supabase start` to regenerate from your local schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          clerk_user_id: string | null;
          email: string | null;
          full_name: string | null;
          role: "admin" | "professor" | "aluno";
          avatar_url: string | null;
          address: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          clerk_user_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "professor" | "aluno";
          avatar_url?: string | null;
          address?: string | null;
          created_at?: string;
        };
        Update: {
          clerk_user_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "professor" | "aluno";
          avatar_url?: string | null;
          address?: string | null;
        };
        Relationships: [];
      };
      alunos: {
        Row: {
          id: string;
          professor_id: string | null;
          profile_id: string | null;
          contact_email: string | null;
          grade: string | null;
          subject_focus: string[] | null;
          notes: string | null;
          monthly_amount: number | null;
          address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id?: string | null;
          profile_id?: string | null;
          contact_email?: string | null;
          grade?: string | null;
          subject_focus?: string[] | null;
          notes?: string | null;
          monthly_amount?: number | null;
          address?: string | null;
          created_at?: string;
        };
        Update: {
          professor_id?: string | null;
          profile_id?: string | null;
          contact_email?: string | null;
          grade?: string | null;
          subject_focus?: string[] | null;
          notes?: string | null;
          monthly_amount?: number | null;
          address?: string | null;
        };
      };
      materiais: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          file_url: string | null;
          subject: string | null;
          grade_level: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          file_url?: string | null;
          subject?: string | null;
          grade_level?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          file_url?: string | null;
          subject?: string | null;
          grade_level?: string | null;
          uploaded_by?: string | null;
        };
        Relationships: [];
      };
      financeiro: {
        Row: {
          id: string;
          aluno_id: string | null;
          amount: number;
          due_date: string | null;
          paid_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          aluno_id?: string | null;
          amount: number;
          due_date?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          aluno_id?: string | null;
          amount?: number;
          due_date?: string | null;
          paid_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      tarefas: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          due_date: string | null;
          material_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          due_date?: string | null;
          material_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          due_date?: string | null;
          material_id?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      aluno_materiais: {
        Row: {
          id: string;
          aluno_id: string;
          material_id: string;
          assigned_by: string | null;
          assigned_at: string;
        };
        Insert: {
          id?: string;
          aluno_id: string;
          material_id: string;
          assigned_by?: string | null;
          assigned_at?: string;
        };
        Update: {
          aluno_id?: string;
          material_id?: string;
          assigned_by?: string | null;
        };
        Relationships: [];
      };
      depoimentos: {
        Row: {
          id: string;
          quote: string;
          author: string;
          sort_order: number;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          quote: string;
          author: string;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          quote?: string;
          author?: string;
          sort_order?: number;
          active?: boolean;
        };
        Relationships: [];
      };
      tarefa_alunos: {
        Row: {
          id: string;
          tarefa_id: string;
          aluno_id: string;
          status: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes: string | null;
          submission_url: string | null;
          submitted_at: string | null;
          reviewed_at: string | null;
          teacher_feedback: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tarefa_id: string;
          aluno_id: string;
          status?: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes?: string | null;
          submission_url?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          teacher_feedback?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tarefa_id?: string;
          aluno_id?: string;
          status?: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes?: string | null;
          submission_url?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          teacher_feedback?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      relatorios_pedagogicos: {
        Row: {
          id: string;
          professor_id: string;
          aluno_id: string;
          disciplinas: string[];
          carga_horaria: string;
          status_conteudo: string;
          engajamento: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          aluno_id: string;
          disciplinas: string[];
          carga_horaria: string;
          status_conteudo: string;
          engajamento?: number | null;
          created_at?: string;
        };
        Update: {
          professor_id?: string;
          aluno_id?: string;
          disciplinas?: string[];
          carga_horaria?: string;
          status_conteudo?: string;
          engajamento?: number | null;
        };
        Relationships: [];
      };
      registros_lista: {
        Row: {
          id: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_aula: string;
          conteudo_ministrado: string;
          quantidade_acertos: number;
          total_questoes: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_aula: string;
          conteudo_ministrado: string;
          quantidade_acertos: number;
          total_questoes: number;
          created_at?: string;
        };
        Update: {
          professor_id?: string;
          aluno_id?: string;
          disciplina?: string;
          data_aula?: string;
          conteudo_ministrado?: string;
          quantidade_acertos?: number;
          total_questoes?: number;
        };
        Relationships: [];
      };
      notas_provas: {
        Row: {
          id: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_prova: string;
          descricao: string;
          nota: number;
          nota_maxima: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id: string;
          aluno_id: string;
          disciplina: string;
          data_prova: string;
          descricao?: string;
          nota: number;
          nota_maxima?: number;
          created_at?: string;
        };
        Update: {
          professor_id?: string;
          aluno_id?: string;
          disciplina?: string;
          data_prova?: string;
          descricao?: string;
          nota?: number;
          nota_maxima?: number;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
